'use client';
import {useState} from 'react';
import {ArrowUpRight,Copy} from 'lucide-react';
import {Field,Pick,useText} from './bridge-ui';
import {industryPairs,employmentTypes} from '@/lib/job-options';
export type JobContext={industry?:string;employment?:string};
export function industryLabel(value:string|undefined,t:(vi:string,en:string)=>string){const p=industryPairs.find(p=>p[0]===value);return p?t(p[1],p[2]):value||t('Chưa rõ','Not sure')}
export function employmentLabel(value:string|undefined,t:(vi:string,en:string)=>string){return value==='Contractor / ABN'?'Contractor':employmentTypes.includes(value||'')?value!:t('Chưa rõ','Not sure')}
export function JobContextFields({value,onChange,only}:{value:JobContext;onChange:(v:JobContext)=>void;only?:'industry'|'employment'}){
 const t=useText(),known=industryPairs.some(p=>p[0]===value.industry),selected=known?value.industry!:value.industry?'other':'unsure';
 const [other,setOther]=useState(known?'':value.industry||'');
 return <>{only!=='employment'&&<><Pick label={t('Ngành nghề','Industry')} value={selected} onChange={v=>onChange({...value,industry:v==='other'?other||'other':v})} options={industryPairs.map(([id,vi,en])=>[id,t(vi,en)])}/>{selected==='other'&&<Field label={t('Ngành khác · tự nhập','Other industry · write your own')}><input maxLength={100} value={other} onChange={e=>{setOther(e.target.value);onChange({...value,industry:e.target.value||'other'})}} placeholder={t('Tên ngành công việc của bạn','Your industry')}/></Field>}</>}{only!=='industry'&&<Pick label={t('Hình thức làm việc','Employment type')} value={value.employment==='Contractor / ABN'?'Contractor':employmentTypes.includes(value.employment||'')?value.employment!:'unsure'} onChange={v=>onChange({...value,employment:v})} options={[...employmentTypes,['unsure',t('Chưa rõ','Not sure')]]}/>}</>
}
export function AbnField({value,onChange}:{value:string;onChange:(v:string)=>void}){const t=useText(),[message,setMessage]=useState('');const digits=value.replace(/\s/g,'');return <section className="abn-field"><Field label={t('ABN của nhà tuyển dụng · tùy chọn','Employer ABN · optional')}><input inputMode="numeric" maxLength={14} pattern="[0-9 ]*" value={value} onChange={e=>{onChange(e.target.value.replace(/[^0-9 ]/g,''));setMessage('')}} placeholder={t('Nhập ABN nếu bạn biết','Enter the ABN if you know it')}/></Field>{digits&&digits.length!==11&&<p className="small muted">{t('Kiểm tra lại: ABN cần 11 chữ số. Bạn cũng có thể để trống.','Check the number: an ABN has 11 digits. You may also leave it blank.')}</p>}<div className="button-row">{digits.length===11&&<button type="button" className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(digits);setMessage(t('Đã sao chép. Dán vào ô tìm kiếm trên ABN Lookup.','Copied. Paste into the search box on ABN Lookup.'))}catch{setMessage(t('Hãy chọn số ABN và sao chép thủ công.','Please select the ABN and copy it manually.'))}}}><Copy size={15}/>{t('Sao chép ABN','Copy ABN')}</button>}<a className="text-button" href="https://abr.business.gov.au/" target="_blank" rel="noreferrer">{t('Tra cứu tại ABN Lookup','Search on ABN Lookup')}<ArrowUpRight size={16}/></a></div><p className="small muted">{t('Chưa được Bridge xác minh. Mở ABN Lookup để tìm bằng ABN hoặc tên doanh nghiệp, rồi đối chiếu tên và trạng thái. App chưa tự lấy kết quả về; ABN không xác nhận điều kiện trả lương.','Not verified by Bridge. Search ABN Lookup by number or business name and compare the name and status. Results are not imported automatically; an ABN does not verify pay conditions.')}</p>{message&&<p className="small" role="status">{message}</p>}</section>}
